import{readFile}from'node:fs/promises';import{WebSerialTransport,parseControllerStatus}from'../src/serial.js';
const firmware=await readFile(new URL('../../ESP32S3 Zero/RoastingControl/RoastingControl.ino',import.meta.url),'utf8');
const appSource=await readFile(new URL('../src/app.js',import.meta.url),'utf8');
if(!/verifyInstalledFirmware/.test(appSource)||!/snapshot\.version===EXPECTED_FIRMWARE\.minimumVersion/.test(appSource)||!/snapshot\.protocol===EXPECTED_FIRMWARE\.protocol/.test(appSource)||!/snapshot\.hardware===EXPECTED_FIRMWARE\.hardware/.test(appSource))throw Error('Post-Flash-Verifikation prüft Version, Protokoll und Hardware nicht vollständig');
if(!/command\s*==\s*"get status"/.test(firmware)||!/void\s+printStatus\s*\(/.test(firmware))throw Error('Echte Firmware implementiert get status nicht');
if(!/command\s*==\s*"get info"/.test(firmware)||!/FIRMWARE_VERSION\s*=\s*"1\.3\.2"/.test(firmware)||!/PROTOCOL_VERSION\s*=\s*3/.test(firmware)||!/CoffeeRoast-Waveshare-ESP32-S3-Zero/.test(firmware))throw Error('Firmware-Versions- oder Hardwarekennung fehlt');
if(/disable failsafe|disableFailsafe/.test(firmware))throw Error('Unsicherer disable-failsafe-Pfad ist noch vorhanden');
if(!/reset failsafe/.test(firmware)||!/healthyReadings\s*>=\s*3/.test(firmware))throw Error('Sicher quittierbarer, verriegelter Failsafe fehlt');
if(!/portENTER_CRITICAL\(&stateMux\)/.test(firmware)||!/failsafeEventPending/.test(firmware))throw Error('FreeRTOS-Status/Serial-Synchronisierung fehlt');
const temperatureTaskBody=firmware.slice(firmware.indexOf('void TemperatureTask'),firmware.indexOf('void setup'));
if(/Serial\./.test(temperatureTaskBody))throw Error('TemperatureTask darf Serial nicht direkt beschreiben');
if(!/appliedRelayValue\s*=\s*\(!outputAbort\s*&&\s*fanValue\s*>=\s*MIN_SAFE_FAN\)/.test(firmware))throw Error('Firmware-SSR-Interlock fehlt');
if(/abortSignal\s*==\s*true[\s\S]{0,180}fanValue\s*=\s*FAILSAFE_FAN/.test(firmware))throw Error('Failsafe darf den Lüfter-Istwert nicht sprunghaft setzen');
const enc=new TextEncoder(),dec=new TextDecoder();
class PortMock{constructor(){this.queue=[];this.waiter=null;this.fan=0;this.heater=0;this.temp=123;this.commands=[]}async open(o){ok(o.baudRate===115200&&o.dataBits===8&&o.stopBits===1&&o.parity==='none','115200/8N1')}getInfo(){return{usbVendorId:0x303a,usbProductId:0x1001}}async setSignals(s){ok(s.dataTerminalReady,'DTR')}emit(text){const value=enc.encode(text);if(this.waiter){const w=this.waiter;this.waiter=null;w({value,done:false})}else this.queue.push(value)}readable={getReader:()=>({read:()=>this.queue.length?Promise.resolve({value:this.queue.shift(),done:false}):new Promise(r=>this.waiter=r),cancel:async()=>{this.waiter?.({done:true});this.waiter=null},releaseLock(){}})};writable={getWriter:()=>({write:async b=>this.handle(dec.decode(b).trim()),releaseLock(){}})};handle(c){this.commands.push(c);if(c==='hello')this.emit('ESP-ROM boot\r\npopcorn roaster\r\n');else if(c==='get status')this.emit(`state=ok,temp=${this.temp},heater=${this.heater},fan=${this.fan},fanTarget=${this.fan},errors=0\r\n`);else if(c==='get temp')this.emit(`${this.temp}\r\n`);else if(c.startsWith('set fan '))this.fan=Number(c.slice(8));else if(c.startsWith('set setpoint '))this.heater=Number(c.slice(13))}async close(){}}
function ok(c,m){if(!c)throw Error(`Fehlgeschlagen: ${m}`)}function near(a,b){return Math.abs(a-b)<.0001}
const parsed=parseControllerStatus('state=ok,temp=100,heater=180.00,fan=42.00,fanTarget=255.00,errors=3');ok(near(parsed.temperature,110)&&parsed.fan===42&&parsed.errors===3&&parsed.compatibility.level==='legacy','Legacy-Statusparser');
const current=parseControllerStatus('state=ok,temp=100,heater=0,fan=50,fanTarget=50,errors=0,healthyReadings=4,failsafeLatched=0,version=1.3.2,protocol=3,hardware=CoffeeRoast-Waveshare-ESP32-S3-Zero');ok(current.compatibility.level==='compatible'&&current.compatibility.compatible,'Aktuelle Firmware kompatibel');
const missingSensor=parseControllerStatus('state=ok,temp=nan,heater=0,fan=0,fanTarget=0,errors=1,healthyReadings=0,failsafeLatched=0,version=1.3.2,protocol=3,hardware=CoffeeRoast-Waveshare-ESP32-S3-Zero');ok(Number.isNaN(missingSensor.temperature)&&missingSensor.compatibility.compatible,'Fehlender Sensor bleibt diagnostizierbarer Controllerstatus');
const wrongHardware=parseControllerStatus('state=ok,temp=100,heater=0,fan=50,fanTarget=50,errors=0,healthyReadings=4,failsafeLatched=0,version=1.3.2,protocol=3,hardware=Other-Board');ok(wrongHardware.compatibility.level==='incompatible'&&!wrongHardware.compatibility.compatible,'Falsche Hardware blockiert');
for(const invalid of ['state=ok,temp=100','state=ok,temp=100,heater=0,fan=50,fanTarget=50,errors=0,version=1.3.2,protocol=3,hardware=CoffeeRoast-Waveshare-ESP32-S3-Zero','state=failsafe,temp=100,heater=0,fan=50,fanTarget=50,errors=21,healthyReadings=0,failsafeLatched=0,version=1.3.2,protocol=3,hardware=CoffeeRoast-Waveshare-ESP32-S3-Zero']){let rejected=false;try{parseControllerStatus(invalid)}catch{rejected=true}ok(rejected,'Ungültiger Status muss verworfen werden')}
const port=new PortMock();Object.defineProperty(globalThis,'navigator',{value:{serial:{requestPort:async()=>port}},configurable:true});const logs=[],transport=new WebSerialTransport(line=>logs.push(line));await transport.connect();ok((await transport.getSnapshot()).rawTemperature===123,'initiale Temperatur');await transport.setFan(255);await transport.setHeater(180);port.emit('Failsafe!\r\n');ok(near(await transport.getTemperature(),135.3),'Failsafe-Zeile nicht als Temperatur');const state=await transport.getSnapshot();ok(state.fan===255&&state.heater===180,'Ist-Ausgänge');ok(logs.some(x=>x.includes('Spontane')),'asynchroner Failsafe');await transport.disconnect(false);console.log('CoffeeRoast Firmware/Web-Protokollparität: OK');
