import{WebSerialTransport,SimulationTransport,EXPECTED_FIRMWARE}from'./serial.js?v=20260711-verify1';
import{loadBuiltInRecipes,parseRecipe}from'./recipes.js?v=20260711-popcorn1';
import{RoastEngine,RoastState}from'./engine.js?v=20260711-autoconnect1';
import{RoastChart,formatTime}from'./chart.js?v=20260711-light1';
const $=id=>document.getElementById(id),engine=new RoastEngine(),chart=new RoastChart($('roastChart'),$('chartTooltip'));
let recipes=[],simulation=false,toastTimer,connecting=false,pendingFirmwareVerification=false;const logLines=[],REMEMBERED_CONTROLLER_KEY='coffeeRoast.rememberedController';

async function boot(){
  $('browserHint').hidden=WebSerialTransport.isSupported();applyTheme(document.documentElement.dataset.theme||'dark');bindEvents();
  try{recipes=await loadBuiltInRecipes();recipes.sort((a,b)=>a.name.localeCompare(b.name,'de'));renderRecipeOptions();selectRecipe(Math.min(Number(localStorage.getItem('coffeeRoast.recipeIndex')||0),recipes.length-1))}catch(error){fail(error)}
  engine.addEventListener('update',event=>render(event.detail));engine.emit();
  await autoConnectRemembered();
}
function applyTheme(theme,persist=false){
  const light=theme==='light';document.documentElement.dataset.theme=light?'light':'dark';
  const button=$('themeButton');if(button){button.textContent=light?'☾ Dunkel':'☀ Hell';button.setAttribute('aria-pressed',String(light))}
  document.querySelector('meta[name="theme-color"]')?.setAttribute('content',light?'#f3eee7':'#0c0d10');
  if(persist)localStorage.setItem('coffeeRoast.theme',light?'light':'dark');chart.draw();
}
function bindEvents(){
  $('connectButton').addEventListener('click',()=>engine.connected?disconnect():connect());$('themeButton').addEventListener('click',()=>applyTheme(document.documentElement.dataset.theme==='light'?'dark':'light',true));$('simulationButton').addEventListener('click',toggleSimulation);$('primaryActionButton').addEventListener('click',primaryAction);$('cooldownButton').addEventListener('click',()=>engine.coolDown('Manuelle Abkühlung'));$('refreshStatusButton').addEventListener('click',refreshStatus);
  $('recipeSelect').addEventListener('change',event=>selectRecipe(Number(event.target.value)));$('loadRecipeButton').addEventListener('click',()=>$('recipeFileInput').click());$('recipeFileInput').addEventListener('change',importRecipe);
  $('fanSlider').addEventListener('input',event=>{engine.initialFanPercent=Number(event.target.value);$('fanSliderValue').textContent=`${event.target.value} %`});
  $('firstCrackInput').addEventListener('change',event=>{engine.expectedFirstCrack=clamp(Number(event.target.value),0,240);event.target.value=engine.expectedFirstCrack;engine.emit()});
  ['autoDropEnabled','dropMode','dropTarget'].forEach(id=>$(id).addEventListener('change',applyAutoDrop));$('resetZoomButton').addEventListener('click',()=>chart.reset());$('exportButton').addEventListener('click',exportCsv);$('uploadRoastButton').addEventListener('click',openUploadRoast);$('uploadRoastConsent').addEventListener('change',event=>$('confirmUploadRoastButton').disabled=!event.target.checked);$('confirmUploadRoastButton').addEventListener('click',event=>{event.preventDefault();if(event.currentTarget.dataset.done==='1')$('uploadRoastDialog').close();else uploadRoast()});['kpInput','kiInput','kdInput'].forEach(id=>$(id).addEventListener('change',applyPid));
  window.addEventListener('beforeunload',event=>{if([RoastState.PREHEATING,RoastState.RUNNING].includes(engine.state)){event.preventDefault();event.returnValue='Der Röster ist aktiv.'}});navigator.serial?.addEventListener('disconnect',()=>{if(engine.connected){engine.enterFailsafe('USB-Verbindung getrennt');showToast('USB-Verbindung getrennt – Failsafe aktiv.',true)}});
  $('firmwareFlashButton').addEventListener('click',()=>{pendingFirmwareVerification=true;setFirmwareVerification('Flashvorgang läuft; anschließend wird Version 1.3.1 geprüft.','checking')});
  $('legacyFirmwareFlashButton').addEventListener('click',()=>{pendingFirmwareVerification=false;setFirmwareVerification('Legacy-Firmware besitzt keine verifizierbare Versionskennung.','warning')});
  $('verifyFirmwareButton').addEventListener('click',()=>verifyInstalledFirmware(true));
  document.addEventListener('closed',event=>{if(event.target?.tagName==='EWT-INSTALL-DIALOG'&&pendingFirmwareVerification){pendingFirmwareVerification=false;setTimeout(()=>verifyInstalledFirmware(false),2500)}});
  const systemMenu=$('systemMenu');systemMenu.addEventListener('toggle',()=>{systemMenu.querySelector('summary').setAttribute('aria-expanded',String(systemMenu.open));if(systemMenu.open&&engine.connected)refreshStatus()});
  document.addEventListener('pointerdown',event=>{if(systemMenu.open&&!systemMenu.contains(event.target))systemMenu.open=false});
  document.addEventListener('keydown',event=>{if(event.key==='Escape'&&systemMenu.open){systemMenu.open=false;systemMenu.querySelector('summary').focus()}});
}
function setFirmwareVerification(message,level='checking'){$('firmwareVerification').textContent=message;$('firmwareVerification').dataset.level=level}
async function verifyInstalledFirmware(requestPort=false){
  if(engine.connected){setFirmwareVerification('Controller zuerst sicher trennen, dann Version prüfen.','error');return}
  const button=$('verifyFirmwareButton');button.disabled=true;setFirmwareVerification(`Starte Controller und prüfe Firmware ${EXPECTED_FIRMWARE.minimumVersion} …`,'checking');
  let verifier,lastError;
  try{
    let ports;
    if(requestPort)ports=[await navigator.serial.requestPort()];
    else ports=(await navigator.serial.getPorts()).filter(port=>{const info=port.getInfo?.()||{};return !info.usbVendorId||info.usbVendorId===0x303a});
    if(!ports.length)throw new Error('Controller nach dem Flashen nicht gefunden. Bitte „Installierte Version prüfen“ anklicken und den ESP auswählen.');
    for(const port of ports){
      verifier=new WebSerialTransport(addLog);
      try{
        await verifier.connect(port);
        const snapshot=await verifier.getSnapshot();
        const exact=snapshot.version===EXPECTED_FIRMWARE.minimumVersion&&snapshot.protocol===EXPECTED_FIRMWARE.protocol&&snapshot.hardware===EXPECTED_FIRMWARE.hardware;
        if(!exact)throw new Error(`Falsche Firmware: ${snapshot.version||'ohne Version'}, Protokoll ${snapshot.protocol||'unbekannt'}, Hardware ${snapshot.hardware||'unbekannt'}. Erwartet ${EXPECTED_FIRMWARE.minimumVersion} / ${EXPECTED_FIRMWARE.protocol} / ${EXPECTED_FIRMWARE.hardware}.`);
        setFirmwareVerification(`✓ Verifiziert: Firmware ${snapshot.version} · Protokoll ${snapshot.protocol} · Waveshare ESP32-S3-Zero`,'success');
        showToast(`Firmware ${snapshot.version} nach dem Flashen verifiziert.`);
        return;
      }catch(error){lastError=error}finally{try{await verifier.disconnect(false)}catch{} verifier=null}
    }
    throw lastError||new Error('Kein antwortender CoffeeRoast-Controller gefunden.');
  }catch(error){setFirmwareVerification(`✗ Verifikation fehlgeschlagen: ${error.message}`,'error');showToast('Flash abgeschlossen, aber Firmwareversion konnte nicht bestätigt werden.',true)}
  finally{if(verifier)try{await verifier.disconnect(false)}catch{}button.disabled=false}
}
function makeTransport(){return simulation?new SimulationTransport(addLog):new WebSerialTransport(addLog)}
async function connect(portOrRequest=true,quiet=false){if(connecting)return;connecting=true;$('connectButton').disabled=true;$('connectionText').textContent=quiet?'Verbinde automatisch …':'ESP32 startet …';$('primaryActionButton').disabled=true;try{engine.setTransport(makeTransport());await engine.connect(portOrRequest);if(!simulation)rememberController(engine.transport.port);if(!quiet)showToast(simulation?'Simulation gestartet.':'CoffeeRoast-Controller verbunden.')}catch(error){if(quiet){addLog(`Autoverbindung nicht möglich: ${error.message}`);$('connectionText').textContent='Controller verbinden'}else fail(error)}finally{connecting=false;$('connectButton').disabled=false;engine.emit()}}
function rememberController(port){const info=port?.getInfo?.()||{};localStorage.setItem(REMEMBERED_CONTROLLER_KEY,JSON.stringify({usbVendorId:info.usbVendorId||0,usbProductId:info.usbProductId||0}))}
async function autoConnectRemembered(){
  if(!WebSerialTransport.isSupported()||engine.connected)return;
  let remembered;try{remembered=JSON.parse(localStorage.getItem(REMEMBERED_CONTROLLER_KEY)||'null')}catch{return}if(!remembered)return;
  try{const ports=await navigator.serial.getPorts(),port=ports.find(candidate=>{const info=candidate.getInfo?.()||{};return(!remembered.usbVendorId||info.usbVendorId===remembered.usbVendorId)&&(!remembered.usbProductId||info.usbProductId===remembered.usbProductId)});if(port)await connect(port,true)}catch(error){addLog(`Autoverbindung nicht verfügbar: ${error.message}`)}
}
async function disconnect(){try{await engine.disconnect();showToast('Controller sicher getrennt.')}catch(error){fail(error)}}
async function toggleSimulation(){if(engine.connected)await disconnect();simulation=!simulation;$('simulationButton').setAttribute('aria-pressed',String(simulation));if(simulation)await connect();else showToast('Hardwaremodus aktiv.')}
async function primaryAction(){if(!engine.connected){await connect();return}if(engine.state===RoastState.IDLE){await engine.beginPreheat();showToast('Lüftervorbereitung gestartet – Heizung bleibt aus.');return}if(engine.state===RoastState.READY){engine.beginRoast();showToast('Röstung gestartet. Bohnen jetzt einfüllen.');return}if(engine.state===RoastState.RUNNING||engine.state===RoastState.PREHEATING){await engine.coolDown('Manuell beendet');return}if(engine.state===RoastState.COOLING){showToast('Abkühlen läuft. Neue Röstung erst unter 60 °C möglich.',true);return}if(engine.state===RoastState.FAILSAFE)showToast('Failsafe aktiv. Ursache beheben und Controller neu verbinden.',true)}
async function refreshStatus(){try{showToast(await engine.refreshStatus()||'Kein Status empfangen.')}catch(error){fail(error)}}

function renderRecipeOptions(){$('recipeSelect').innerHTML=recipes.map((recipe,index)=>`<option value="${index}">${escapeHtml(recipe.name)}</option>`).join('')}
function selectRecipe(index){if(!recipes[index])return;$('recipeSelect').value=String(index);engine.setRecipe(recipes[index]);localStorage.setItem('coffeeRoast.recipeIndex',String(index));updateRecipeCard(recipes[index]);chart.reset()}
function updateRecipeCard(recipe){$('recipeDescription').textContent=recipe.description;$('recipeDuration').textContent=formatTime(recipe.duration);$('recipeEndTemp').textContent=`${Math.round(recipe.endTemp)} °C`;$('recipePointCount').textContent=String(recipe.points.length);$('kpInput').value=fmt(recipe.pid.kp,3);$('kiInput').value=fmt(recipe.pid.ki,3);$('kdInput').value=fmt(recipe.pid.kd,3);$('firstCrackInput').value=String(Math.round(recipe.expectedFirstCrack||208))}
async function importRecipe(event){const file=event.target.files?.[0];if(!file)return;try{const recipe=parseRecipe(await file.text(),file.name);recipes.push(recipe);renderRecipeOptions();selectRecipe(recipes.length-1);showToast(`${recipe.name} geladen.`)}catch(error){fail(error)}finally{event.target.value=''}}
function applyAutoDrop(){const enabled=$('autoDropEnabled').checked,mode=$('dropMode').value,max=mode==='time'?1199:300;$('dropTarget').max=String(max);$('dropTarget').value=String(clamp(Number($('dropTarget').value),1,max));$('dropUnit').textContent=mode==='time'?'s':'°C';engine.setAutoDrop(enabled,mode,Number($('dropTarget').value))}
function applyPid(){engine.pid.configure({kp:Number($('kpInput').value),ki:Number($('kiInput').value),kd:Number($('kdInput').value),future:engine.recipe?.pid.future||40});showToast('PID-Werte übernommen.')}

function render(snapshot){
  const meta=snapshot.connected?stateMeta(snapshot.state):{title:'Nicht verbunden',subtitle:simulation?'Simulation starten oder Hardwaremodus wählen.':'CoffeeRoast-Controller über USB verbinden.',color:'#686d75'};$('stateTitle').textContent=meta.title;$('stateSubtitle').textContent=meta.subtitle;$('stateIcon').style.color=meta.color;
  $('currentTemp').textContent=number(snapshot.temperature);$('targetTemp').textContent=snapshot.target>0?number(snapshot.target):'—';$('elapsedTime').textContent=formatTime(snapshot.elapsed);$('heaterPercent').textContent=String(Math.round(snapshot.heater/2.55));$('fanPercent').textContent=String(Math.round(snapshot.fan/2.55));
  $('tempTrend').textContent=Number.isFinite(snapshot.ror)?`${signed(snapshot.ror)} °C/min RoR`:'RoR nach 30 Sekunden';$('targetDelta').textContent=Number.isFinite(snapshot.temperature)&&snapshot.target>0?`${signed(snapshot.target-snapshot.temperature)} °C Differenz`:'Profil inaktiv';$('remainingTime').textContent=roastStatusLine(snapshot);
  $('outputHint').textContent=snapshot.state===RoastState.FAILSAFE?'Failsafe-Ausgänge':snapshot.state===RoastState.PREHEATING?(snapshot.fan>=40?'Lüftergeschwindigkeit bestätigt · Heizung aus':'Lüfter läuft an · Heizung aus'):snapshot.heater>0?'Heizung aktiv':'Heizung aus';$('autoDropBadge').textContent=snapshot.autoDropEnabled?(snapshot.autoDropMode==='time'?`bei ${formatTime(snapshot.autoDropTarget)}`:`bei ${Math.round(snapshot.autoDropTarget)} °C`):'deaktiviert';
  const compatibility=snapshot.firmwareCompatibility||{level:'unknown',label:'Nicht geprüft',compatible:false,reason:''};$('connectionText').textContent=snapshot.connected?(snapshot.portName||'Verbunden'):'Controller verbinden';$('connectButton').classList.toggle('connected',snapshot.connected);$('firmwareFlashButton').disabled=snapshot.connected;$('legacyFirmwareFlashButton').disabled=snapshot.connected;$('firmwareHint').textContent=snapshot.connected?'Controller vor dem Flashen zuerst sicher trennen.':'Flashen überschreibt Programm und Einstellungen.';$('diagConnection').textContent=snapshot.connected?'Verbunden':'Getrennt';$('diagCompatibility').textContent=compatibility.label;$('diagCompatibility').title=compatibility.reason;$('diagCompatibility').dataset.level=compatibility.level;$('diagFirmwareVersion').textContent=snapshot.firmwareVersion?`${snapshot.firmwareVersion} · Protokoll ${snapshot.protocolVersion}`:(snapshot.connected?'Legacy ohne Kennung':'—');$('diagFirmware').textContent=snapshot.status||'—';$('diagErrors').textContent=String(snapshot.sensorErrors);$('diagLastResponse').textContent=lastLogResponse();$('safetyBadge').textContent=!compatibility.compatible&&snapshot.connected?'Firmware blockiert':snapshot.state===RoastState.FAILSAFE?'Failsafe':snapshot.heater>0?'Heizung aktiv':'Sicher';$('safetyBadge').classList.toggle('safe',compatibility.compatible&&snapshot.state!==RoastState.FAILSAFE&&snapshot.heater===0);
  $('uploadRoastButton').disabled=snapshot.samples.length<2;updateActions(snapshot);updateStepper(snapshot.state);chart.setData(snapshot);
}
function updateActions(snapshot){const button=$('primaryActionButton'),cool=$('cooldownButton'),firmwareAllowed=snapshot.firmwareCompatibility?.compatible!==false;button.disabled=!snapshot.recipe||snapshot.state===RoastState.FAILSAFE||snapshot.state===RoastState.COOLING||(snapshot.connected&&!firmwareAllowed);cool.disabled=!snapshot.connected||![RoastState.PREHEATING,RoastState.READY,RoastState.RUNNING].includes(snapshot.state);let icon='▶',text='Lüfter vorbereiten',sub='Ohne Heizung starten';if(!snapshot.connected){text='Controller verbinden';sub=simulation?'Simulation starten':'USB-Gerät auswählen'}else if(!firmwareAllowed){icon='!';text='Firmware nicht kompatibel';sub=snapshot.firmwareCompatibility?.reason||'Firmware aktualisieren'}else if(snapshot.state===RoastState.PREHEATING){icon='■';text='Lüftervorbereitung abbrechen';sub='Heizung bleibt aus'}else if(snapshot.state===RoastState.READY){text='Röstung starten';sub='Bohnen einfüllen und Profil starten'}else if(snapshot.state===RoastState.RUNNING){icon='■';text='Röstung beenden';sub='Sofort in Abkühlung wechseln'}else if(snapshot.state===RoastState.COOLING){text='Abkühlen läuft';sub='Neue Röstung erst unter 60 °C'}else if(snapshot.state===RoastState.FAILSAFE){icon='!';text='FAILSAFE';sub='Neu verbinden nach Fehlerbehebung'}$('primaryActionIcon').textContent=icon;$('primaryActionText').textContent=text;$('primaryActionSubtext').textContent=sub}
function updateStepper(state){['stepConnect','stepPreheat','stepRoast','stepCool'].forEach(id=>$(id).classList.remove('active','done'));if(engine.connected)$('stepConnect').classList.add('done');if(state===RoastState.PREHEATING)$('stepPreheat').classList.add('active');if(state===RoastState.READY)$('stepPreheat').classList.add('done');if(state===RoastState.RUNNING){$('stepPreheat').classList.add('done');$('stepRoast').classList.add('active')}if(state===RoastState.COOLING){$('stepPreheat').classList.add('done');$('stepRoast').classList.add('done');$('stepCool').classList.add('active')}['phasePreheat','phaseRoast','phaseCool'].forEach(id=>$(id).classList.remove('active'));if(state===RoastState.PREHEATING||state===RoastState.READY)$('phasePreheat').classList.add('active');if(state===RoastState.RUNNING)$('phaseRoast').classList.add('active');if(state===RoastState.COOLING)$('phaseCool').classList.add('active')}

function openUploadRoast(){if(engine.samples.length<2){showToast('Noch keine Röstkurve zum Hochladen.',true);return}const button=$('confirmUploadRoastButton');button.dataset.done='0';button.textContent='Kurve hochladen';button.disabled=true;$('uploadRoastConsent').checked=false;$('uploadRoastNote').value='';$('uploadRoastStatus').textContent=`${engine.samples.length} Messpunkte sind bereit. Nach dem Upload erhältst du eine Analyse-ID.`;$('uploadRoastDialog').showModal()}
async function uploadRoast(){
  const button=$('confirmUploadRoastButton');if(!$('uploadRoastConsent').checked||engine.samples.length<2)return;button.disabled=true;button.textContent='Wird hochgeladen …';
  const snapshot=engine.snapshot(),payload={clientVersion:'CoffeeRoast V2',recipe:{name:snapshot.recipe?.name||'Unbekannt',fileName:snapshot.recipe?.fileName||''},note:$('uploadRoastNote').value,firmware:snapshot.firmwareVersion||'',protocol:String(snapshot.protocolVersion||''),hardware:snapshot.hardwareId||'',samples:snapshot.samples.map(s=>({time:s.time,temperature:s.temperature,target:s.target,ror:Number.isFinite(s.ror)?s.ror:null,heater:s.heater,fan:s.fan,phase:s.phase||'',state:s.state||''}))};
  try{const response=await fetch('/api/roasts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);button.dataset.done='1';button.textContent='Schließen';button.disabled=false;$('uploadRoastStatus').textContent=`Upload gespeichert. Analyse-ID: ${result.id} · Dauer ${formatTime(result.analysis?.durationSeconds||0)} · Maximum ${fmt(result.analysis?.maxTemperature,1)} °C`;showToast(`Röstkurve gespeichert: ${result.id}`)}catch(error){button.textContent='Erneut versuchen';button.disabled=false;$('uploadRoastStatus').textContent=`Upload fehlgeschlagen: ${error.message}`}
}

function exportCsv(){if(!engine.samples.length){showToast('Noch keine Messdaten zum Exportieren.',true);return}const rows=['Zeit_s;Zeit;Temperatur_C;Ziel_C;RoR_C_min;Heizung_PWM;Heizung_Prozent;Luefter_PWM;Luefter_Prozent;Phase;Status'];engine.samples.forEach(s=>rows.push([s.time.toFixed(1),formatTime(s.time),fmt(s.temperature,2),fmt(s.target,2),fmt(s.ror,2),Math.round(s.heater),Math.round(s.heater/2.55),Math.round(s.fan),Math.round(s.fan/2.55),s.phase||'',s.state].join(';')));const blob=new Blob(['\uFEFF'+rows.join('\r\n')],{type:'text/csv;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`CoffeeRoast_${new Date().toISOString().replace(/[:.]/g,'-')}.csv`;link.click();URL.revokeObjectURL(link.href);showToast('CSV exportiert.')}
function addLog(line){logLines.unshift(line);if(logLines.length>100)logLines.length=100;$('serialLog').textContent=logLines.join('\n')}
function lastLogResponse(){return logLines.find(line=>line.includes('←'))?.split('←')[1]?.trim()||'—'}
function roastStatusLine(s){if(s.state!==RoastState.RUNNING)return s.state===RoastState.PREHEATING?'Lüftergeschwindigkeit wird eingestellt':s.state===RoastState.READY?'Bereit zum Start':'Noch nicht gestartet';const stop=s.autoDropEnabled&&s.autoDropMode==='time'?Math.min(s.autoDropTarget,s.recipe?.duration??s.autoDropTarget):s.recipe?.duration,parts=[phaseLabel(s.phase)];if(Number.isFinite(stop))parts.push(`${formatTime(Math.max(0,stop-s.elapsed))} verbleibend`);if(s.firstCrackSecond>=0){const since=Math.max(0,s.elapsed-s.firstCrackSecond),dtr=s.elapsed>0?since/s.elapsed*100:0;parts.push(`FC+${formatTime(since)} · DTR ${fmt(dtr,1)}%`)}return parts.join(' · ')}
function phaseLabel(phase){return({charging:'🫘 Charging',drying:'💧 Drying',maillard:'🟤 Maillard','first-crack':'💥 First Crack',development:'☕ Development','second-crack':'⚠️ Second Crack',preparation:'Lüftervorbereitung',ready:'Bereit',cooling:'❄️ Cooling'})[phase]||'Röstung'}
function stateMeta(state){return({idle:{title:'Bereit',subtitle:'Rezept wählen und sicher starten.',color:'#66d19e'},preheating:{title:'Lüftervorbereitung',subtitle:'Lüftergeschwindigkeit wird bestätigt; die Heizung bleibt vollständig aus.',color:'#e8c55b'},ready:{title:'Bereit zum Rösten',subtitle:'Bohnen einfüllen und Röstprofil starten.',color:'#66d19e'},running:{title:'Röstung läuft',subtitle:'Temperaturprofil wird automatisch geregelt.',color:'#e8793e'},cooling:{title:'Abkühlen',subtitle:'Heizung aus, Lüfter führt Wärme ab.',color:'#73a8ff'},failsafe:{title:'FAILSAFE',subtitle:'Heizung aus. Ursache vor Neustart beheben.',color:'#ff635f'}})[state]}
function showToast(message,error=false){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.toggle('error',error);$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,4200)}
function fail(error){console.error(error);showToast(error?.message||String(error),true)}function number(v){return Number.isFinite(v)?String(Math.round(v)):'—'}function fmt(v,d=1){return Number.isFinite(Number(v))?Number(v).toFixed(d).replace(/\.?0+$/,''):'—'}function signed(v){return`${v>=0?'+':''}${fmt(v,1)}`}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
boot();
